// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzWoDU8BIIxuq8H61v-arMF_U5nwmQWg',
    appId: '1:226606351642:web:72882d9fe25410dbab58a3',
    messagingSenderId: '226606351642',
    projectId: 'agriconnect-6f2c3',
    authDomain: 'agriconnect-6f2c3.firebaseapp.com',
    storageBucket: 'agriconnect-6f2c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzmH9GUi9yPaRQ3zo77sS2mDZiW0j4zNk',
    appId: '1:226606351642:android:09b0d84d72ffba7bab58a3',
    messagingSenderId: '226606351642',
    projectId: 'agriconnect-6f2c3',
    storageBucket: 'agriconnect-6f2c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYs5TLbUw4-ohCa6ITpf5aZvyvl9HET0',
    appId: '1:226606351642:ios:71137f3dfb5822a6ab58a3',
    messagingSenderId: '226606351642',
    projectId: 'agriconnect-6f2c3',
    storageBucket: 'agriconnect-6f2c3.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYs5TLbUw4-ohCa6ITpf5aZvyvl9HET0',
    appId: '1:226606351642:ios:71137f3dfb5822a6ab58a3',
    messagingSenderId: '226606351642',
    projectId: 'agriconnect-6f2c3',
    storageBucket: 'agriconnect-6f2c3.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzWoDU8BIIxuq8H61v-arMF_U5nwmQWg',
    appId: '1:226606351642:web:4e639c57a7243bbaab58a3',
    messagingSenderId: '226606351642',
    projectId: 'agriconnect-6f2c3',
    authDomain: 'agriconnect-6f2c3.firebaseapp.com',
    storageBucket: 'agriconnect-6f2c3.firebasestorage.app',
  );
}
